[theme]
base = "dark"
primaryColor = "#00B4D8"
backgroundColor = "#0B132B"
secondaryBackgroundColor = "#1C2541"
textColor = "#F8FAFC"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
